In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3], dtype='int32')
b = np.array([[1, 2, 3], [4 ,5 ,6]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
a.size

3

In [ ]:
a.nbytes

12

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.itemsize

4

In [ ]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
c[0, 1, 0]

np.int64(3)

In [ ]:
c[:, 1, :]

array([[3, 4],
       [7, 8]])

In [ ]:
c[:, 1, :] = [[97, 98], [99, 100]]
print(c)

[[[  1   2]
  [ 97  98]]

 [[  5   6]
  [ 99 100]]]


In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
np.full(3, 99)

array([99, 99, 99])

In [ ]:
np.full((3, 3), 55)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5, 3)

array([[0.46455079, 0.73134014, 0.49414829],
       [0.14003093, 0.45814934, 0.67230575],
       [0.49973213, 0.02239488, 0.04007364],
       [0.68959141, 0.26251919, 0.46656641],
       [0.81556797, 0.76243835, 0.52100947]])

In [ ]:
np.random.randint(29, 100, 6)

array([79, 48, 51, 97, 51, 82])

In [ ]:
np.random.randint(1, 6, size=(4,4))

array([[5, 1, 2, 4],
       [5, 5, 1, 4],
       [4, 2, 4, 1],
       [1, 1, 4, 3]])

In [ ]:
d = np.array([1, 2, 3])
e = np.repeat(d, 3)
print(e)

[1 1 1 2 2 2 3 3 3]


In [ ]:
f = np.array([[1,2]])
g = np.repeat(f, 4, axis=0)
print(g)

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [ ]:
f = np.array([[1,2]])
g = np.repeat(f, 4, axis=1)
print(g)

[[1 1 1 1 2 2 2 2]]


In [ ]:
h = np.ones((5, 5))

i = np.zeros((3, 3))
i[1, 1] = 9

h[1:4, 1:4] = i
print(h)
# print(h[1:-1, 1:-1])
# print(h[0:2, 0:3])

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
test = np.array([[1, 2, 3], [4, 5, 6]])
# print(test[0])
# print(test[0:2, 0:1])
# print(np.sum(test)/test.size)
# print(np.matmul(test, test))
print(test.reshape((3, 2)))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
practice = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
print(practice)
# print(practice[2:4, 0:2])
# result = practice[0:4, 1:]
# print(result)
# print(practice[[0, 1, 2, 3], [1, 2, 3, 4]])
# print(practice[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
print(practice[[0, 4, 5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 4  5]
 [24 25]
 [29 30]]


In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
# arr[1:4:2]
# arr[::2]
arr.view()

array([10, 15, 20, 25, 30, 35, 40])